# Generated by Django 4.2.6 on 2023-10-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0002_post_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
